"""
upload.py
---------
Landing / resume upload experience. Handles the PDF -> text ->
analyze_resume_v2 pipeline with premium loading states.
"""

import os
import tempfile
import streamlit as st

from utils.backend_bridge import (
    read_resume_pdf,
    run_resume_analysis,
    persist_resume_data,
    BackendError,
)


def render_hero():
    st.markdown(
        """
        <div class="hero-wrap">
            <div class="hero-badge">✦ Multi-Agent AI Career Platform</div>
            <div class="hero-title">Land your placement<br/>with an AI team behind you</div>
            <div class="hero-subtitle">
                Upload your resume once. Get an ATS-grade analysis, a personalized
                12-week roadmap, and interview prep — generated by a coordinated
                system of specialist AI agents.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    chips = ["ATS Scoring", "Skill Gap Analysis", "12-Week DSA Plan", "Mock Interview Questions", "Curated Resources"]
    chip_html = "".join(f'<span class="feature-chip">{c}</span>' for c in chips)
    st.markdown(f'<div style="text-align:center; margin-bottom: 2.2rem;">{chip_html}</div>', unsafe_allow_html=True)


def render_upload_zone():
    st.markdown('<div class="glass-card" style="max-width: 620px; margin: 0 auto; padding: 2rem;">', unsafe_allow_html=True)
    st.markdown(
        '<div class="section-label">Step 1</div>'
        '<div class="section-heading" style="margin-bottom: 1rem;">Upload your resume</div>',
        unsafe_allow_html=True,
    )

    uploaded_file = st.file_uploader(
        "Upload Resume PDF",
        type=["pdf"],
        label_visibility="collapsed",
        key="resume_uploader",
    )

    if uploaded_file is not None:
        st.markdown(
            f'<div style="font-size:0.85rem; color: var(--text-secondary); margin: 0.6rem 0 1rem 0;">'
            f'📄 {uploaded_file.name} · {round(len(uploaded_file.getvalue()) / 1024, 1)} KB</div>',
            unsafe_allow_html=True,
        )

        analyze_clicked = st.button("Analyze Resume →", type="primary", use_container_width=True)

        if analyze_clicked:
            _run_analysis_pipeline(uploaded_file)

    st.markdown('</div>', unsafe_allow_html=True)


def _run_analysis_pipeline(uploaded_file):
    progress_placeholder = st.empty()

    try:
        with progress_placeholder.container():
            with st.spinner("Extracting text from PDF..."):
                with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
                    tmp.write(uploaded_file.getvalue())
                    tmp_path = tmp.name
                try:
                    resume_text = read_resume_pdf(tmp_path)
                finally:
                    if os.path.exists(tmp_path):
                        os.remove(tmp_path)

            if not resume_text or not resume_text.strip():
                st.error("Couldn't extract any text from this PDF. Try a different file.")
                return

            with st.spinner("Resume Agent is analyzing your profile..."):
                resume_data = run_resume_analysis(resume_text)

        st.session_state["resume_text"] = resume_text
        st.session_state["resume_data"] = resume_data
        st.session_state["active_page"] = "overview"
        persist_resume_data(resume_data)

        progress_placeholder.empty()
        st.success("Analysis complete.")
        st.rerun()

    except BackendError as e:
        progress_placeholder.empty()
        st.error(str(e))
    except Exception as e:
        progress_placeholder.empty()
        st.error(f"Something went wrong during analysis. ({e})")