"""
interview_prep.py
------------------
Calls generate_interview_questions(resume_data, target_role) and
renders the markdown output. Reuses target_role from session state
(set on Roadmap page) when available.
"""

import streamlit as st

from components.cards import section_header, empty_state, glass_card_start, glass_card_end, render_markdown_block
from utils.backend_bridge import run_interview_questions, BackendError

COMMON_ROLES = [
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Data Analyst",
    "Data Scientist",
    "DevOps Engineer",
    "SDE - Product Based",
    "Custom...",
]


def render():
    resume_data = st.session_state.get("resume_data")

    section_header(
        "Interview Prep",
        "Practice questions",
        "Generated by the Interview Agent — technical, HR, behavioral, project, and topic-wise questions.",
    )

    if not resume_data:
        empty_state("◎", "No resume analyzed yet", "Upload and analyze your resume first to generate interview questions.")
        return

    glass_card_start()
    c1, c2 = st.columns([3, 1])
    with c1:
        default_role = st.session_state.get("target_role")
        suggested = resume_data.get("recommended_roles", [])
        default_options = list(dict.fromkeys(suggested + COMMON_ROLES))
        default_index = default_options.index(default_role) if default_role in default_options else 0
        selected_role = st.selectbox(
            "Target Role", default_options, index=default_index,
            key="interview_role_select", label_visibility="collapsed",
        )
        if selected_role == "Custom...":
            selected_role = st.text_input("Enter target role", key="interview_custom_role", placeholder="e.g. Machine Learning Engineer")

    with c2:
        generate_clicked = st.button("Generate Questions →", type="primary", use_container_width=True)
    glass_card_end()

    if generate_clicked and selected_role:
        st.session_state["target_role"] = selected_role
        try:
            with st.spinner(f"Interview Agent is preparing questions for {selected_role}..."):
                interview_text = run_interview_questions(resume_data, selected_role)
            st.session_state["interview_text"] = interview_text
            st.rerun()
        except BackendError as e:
            st.error(str(e))

    interview_text = st.session_state.get("interview_text")
    if interview_text:
        glass_card_start()
        render_markdown_block(interview_text)
        glass_card_end()
    else:
        empty_state("◎", "No questions generated yet", "Select a target role above and click Generate Questions.")