"""
resume_analysis.py
-------------------
Full breakdown of analyze_resume_v2() output.
"""

import streamlit as st

from components.cards import (
    section_header,
    ats_score_display,
    pill_list,
    divider,
    empty_state,
    glass_card_start,
    glass_card_end,
)


def render():
    resume_data = st.session_state.get("resume_data")

    section_header(
        "Resume Analysis",
        "Detailed breakdown",
        "Generated by the Resume Agent from your uploaded PDF.",
    )

    if not resume_data:
        empty_state("▤", "No resume analyzed yet", "Upload your resume from the Overview tab to see your analysis here.")
        return

    glass_card_start()
    ats_score_display(resume_data.get("ats_score", 0))
    glass_card_end()

    col1, col2 = st.columns(2)

    with col1:
        glass_card_start()
        st.markdown('<div class="section-label">Strengths</div>', unsafe_allow_html=True)
        strengths = resume_data.get("strengths", [])
        if strengths:
            for s in strengths:
                st.markdown(f'<div style="padding: 0.3rem 0; color: var(--text-secondary); font-size: 0.9rem;">✓&nbsp;&nbsp;{s}</div>', unsafe_allow_html=True)
        else:
            st.markdown('<div style="color: var(--text-tertiary); font-size: 0.85rem;">None identified</div>', unsafe_allow_html=True)
        glass_card_end()

    with col2:
        glass_card_start()
        st.markdown('<div class="section-label">Weaknesses</div>', unsafe_allow_html=True)
        weaknesses = resume_data.get("weaknesses", [])
        if weaknesses:
            for w in weaknesses:
                st.markdown(f'<div style="padding: 0.3rem 0; color: var(--text-secondary); font-size: 0.9rem;">✕&nbsp;&nbsp;{w}</div>', unsafe_allow_html=True)
        else:
            st.markdown('<div style="color: var(--text-tertiary); font-size: 0.85rem;">None identified</div>', unsafe_allow_html=True)
        glass_card_end()

    glass_card_start()
    st.markdown('<div class="section-label">Skills</div>', unsafe_allow_html=True)
    pill_list(resume_data.get("skills", []), variant="accent")
    glass_card_end()

    glass_card_start()
    st.markdown('<div class="section-label">Missing Skills</div>', unsafe_allow_html=True)
    pill_list(resume_data.get("missing_skills", []), variant="danger")
    glass_card_end()

    glass_card_start()
    st.markdown('<div class="section-label">Recommended Roles</div>', unsafe_allow_html=True)
    pill_list(resume_data.get("recommended_roles", []), variant="success")
    glass_card_end()

    glass_card_start()
    st.markdown('<div class="section-label">Projects</div>', unsafe_allow_html=True)
    projects = resume_data.get("projects", [])
    if projects:
        for i, p in enumerate(projects):
            st.markdown(
                f'<div style="padding: 0.55rem 0; border-bottom: 1px solid var(--border-subtle); font-size: 0.9rem; color: var(--text-primary);">{i+1}. {p}</div>',
                unsafe_allow_html=True,
            )
    else:
        st.markdown('<div style="color: var(--text-tertiary); font-size: 0.85rem;">No projects identified</div>', unsafe_allow_html=True)
    glass_card_end()