"""
roadmap.py
----------
Calls generate_roadmap_v2(resume_data, target_role) and renders the
markdown roadmap. Lets the user choose / type their target role.
"""

import streamlit as st

from components.cards import section_header, empty_state, glass_card_start, glass_card_end, render_markdown_block
from utils.backend_bridge import run_roadmap_generation, BackendError

COMMON_ROLES = [
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Data Analyst",
    "Data Scientist",
    "DevOps Engineer",
    "SDE - Product Based",
    "Custom...",
]


def render():
    resume_data = st.session_state.get("resume_data")

    section_header(
        "Roadmap",
        "Your placement roadmap",
        "Generated by the Roadmap Agent based on your resume and target role.",
    )

    if not resume_data:
        empty_state("◷", "No resume analyzed yet", "Upload and analyze your resume first to generate a roadmap.")
        return

    glass_card_start()
    c1, c2 = st.columns([3, 1])
    with c1:
        suggested = resume_data.get("recommended_roles", [])
        default_options = list(dict.fromkeys(suggested + COMMON_ROLES))
        selected_role = st.selectbox("Target Role", default_options, key="roadmap_role_select", label_visibility="collapsed", placeholder="Select target role")

        if selected_role == "Custom...":
            selected_role = st.text_input("Enter target role", key="roadmap_custom_role", placeholder="e.g. Machine Learning Engineer")

    with c2:
        generate_clicked = st.button("Generate Roadmap →", type="primary", use_container_width=True)
    glass_card_end()

    if generate_clicked and selected_role:
        st.session_state["target_role"] = selected_role
        try:
            with st.spinner(f"Roadmap Agent is building your plan for {selected_role}..."):
                roadmap_text = run_roadmap_generation(resume_data, selected_role)
            st.session_state["roadmap_text"] = roadmap_text
            st.rerun()
        except BackendError as e:
            st.error(str(e))

    roadmap_text = st.session_state.get("roadmap_text")
    if roadmap_text:
        glass_card_start()
        render_markdown_block(roadmap_text)
        glass_card_end()
    else:
        empty_state("◷", "No roadmap generated yet", "Select a target role above and click Generate Roadmap.")